### ISSUE TITLE
Numpy is used inside nose-py3 but not installed automatically with a package

### ISSUE THREAD

**Issue by vsbogd** [atsb/nose-py3#1]
Version of `nose-py3` installed is `1.4.0`. When I am trying to run nose I receive the following exception:
```
$ python -m nose --version
Traceback (most recent call last):
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/site-packages/nose/__init__.py", line 1, in <module>
    from nose.core import collector, main, run, run_exit, runmodule
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/site-packages/nose/core.py", line 11, in <module>
    from nose.config import Config, all_config_files
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/site-packages/nose/config.py", line 11, in <module>
    from nose.plugins.manager import NoPlugins
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/site-packages/nose/plugins/__init__.py", line 184, in <module>
    from nose.plugins.base import Plugin
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/site-packages/nose/plugins/base.py", line 6, in <module>
    from nose.util import tolist
  File "/home/vital/miniconda3/envs/hyperon/lib/python3.10/site-packages/nose/util.py", line 13, in <module>
    from numpy import str
ModuleNotFoundError: No module named 'numpy'
```

There is an import from `numpy` package:
https://github.com/atsb/nose-py3/blob/e64ad91c2947ec31d8a0165814a245d179988bb5/nose/util.py#L13

But `numpy` is not installed automatically with a package.

**Comment by atsb** [comment]
Thanks!  I will take a look at this

**Comment by atsb** [comment]
Ok, fixed it.  I will do a git push later and will update pypi with a new version 1.4.1 soon.

**Comment by vsbogd** [comment]
Cool, thanks!

**Comment by atsb** [comment]
Ok, nose-py3 1.4.3 (I had previously used two releases that are now deleted) is now on pip.  Thanks so much for the report!

**Comment by vsbogd** [comment]
Checked, it works, thanks again!
