### ISSUE TITLE
Error while using `raises`

### ISSUE THREAD

**Issue by dannykomo** [atsb/nose-py3#10]
The decorator "raises" does not work.

```python
# a.py
from nose.tools import raises

def f():
    raise TypeError("a")


@raises(TypeError)
def test():
    f()
```

Error:
```d
$ nosetests -vs a.py


Failure: AttributeError ('function' object has no attribute 'func_code') ... ERROR

======================================================================
ERROR: Failure: AttributeError ('function' object has no attribute 'func_code')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/py-venv/wf/lib/python3.7/site-packages/nose/failure.py", line 40, in runTest
    raise self.exc_class(None).with_traceback(self.tb)
  File "/opt/py-venv/wf/lib/python3.7/site-packages/nose/loader.py", line 423, in loadTestsFromName
    addr.filename, addr.module)
  File "/opt/py-venv/wf/lib/python3.7/site-packages/nose/importer.py", line 48, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/opt/py-venv/wf/lib/python3.7/site-packages/nose/importer.py", line 95, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/moravenov/repos/wfcommon/a.py", line 7, in <module>
    @raises(TypeError)
  File "/opt/py-venv/wf/lib/python3.7/site-packages/nose/tools/nontrivial.py", line 72, in decorate
    newfunc = make_decorator(func)(newfunc)
  File "/opt/py-venv/wf/lib/python3.7/site-packages/nose/tools/nontrivial.py", line 29, in decorate
    newfunc.compat_co_firstlineno = func.func_code.co_firstlineno
AttributeError: None
-------------------- >> begin captured logging << --------------------
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)

```

### Suggested sollution:
in the file `nose/tools/nontrivial.py` on line 29:

change: `newfunc.compat_co_firstlineno = func.func_code.co_firstlineno`
to be:     `newfunc.compat_co_firstlineno = func.__code__.co_firstlineno`

since `func_code` has been renamed to `__code__`
according to: https://stackoverflow.com/a/5497076

**Comment by atsb** [comment]
Yep, that looks like a good solution.  Thanks for bringing this to my attention.
