### ISSUE TITLE
AttributeError since upgrade from 1.4.0 -> 1.4.3

### ISSUE THREAD

**Issue by ghost** [atsb/nose-py3#2]
Hi, I get the exception below when upgrading nose-py3 from 1.4.0 to 1.4.3:

```
(daproject) [dauser@desk004 django]$ python --version
Python 3.10.3
(daproject) [dauser@desk004 django]$ pip freeze | grep -i nose
django-nose==1.4.7
nose-py3==1.4.3
(daproject) [dauser@desk004 django]$ nosetests positions --verbose --nocapture --verbosity=2
Traceback (most recent call last):
  File "/home/dauser/projects/daproject/venv/daproject/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/core.py", line 117, in __init__
    unittest.TestProgram.__init__(
  File "/home/dauser/installed/fedora_f35/python3.10.3/usr/local/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/core.py", line 178, in parseArgs
    self.createTests()
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/core.py", line 192, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/loader.py", line 484, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/home/dauser/installed/fedora_f35/python3.10.3/usr/local/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/dauser/installed/fedora_f35/python3.10.3/usr/local/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/loader.py", line 434, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/loader.py", line 357, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
AttributeError: 'map' object has no attribute 'extend'
```

**Comment by atsb** [comment]
Hmmm this is really strange.  I gave 1.4.3 a good bashing on my system before I uploaded the package and had no issues with it not running tests.

I am assuming that these tests worked previously on 1.4.0?

**Comment by ghost** [comment]
> I am assuming that these tests worked previously on 1.4.0?

Yes, rolling back to 1.4.0 removes this exception for me.

To be precise: I usually run this using django's testing facility by running

`python manage.py test positions --keepdb --verbose --nocapture`

The first line of output of that statement is
`nosetests positions --verbose --nocapture --verbosity=2`

Using 1.4.0 it then proceeds as expected, whereas using 1.4.3 leads to the above exception with a slightly longer stacktrace:

```
(daproject) [dauser@desk004 django]$ python manage.py test positions --keepdb --verbose --nocapture
nosetests positions --verbose --nocapture --verbosity=2
Traceback (most recent call last):
  File "/home/dauser/projects/daproject/src/django/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
    super().run_from_argv(argv)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/django/core/management/commands/test.py", line 68, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/django_nose/runner.py", line 308, in run_tests
    result = self.run_suite(nose_argv)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/django_nose/runner.py", line 244, in run_suite
    nose.core.TestProgram(argv=nose_argv, exit=False,
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/core.py", line 117, in __init__
    unittest.TestProgram.__init__(
  File "/home/dauser/installed/fedora_f35/python3.10.3/usr/local/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/core.py", line 178, in parseArgs
    self.createTests()
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/core.py", line 192, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/loader.py", line 484, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/home/dauser/installed/fedora_f35/python3.10.3/usr/local/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/dauser/installed/fedora_f35/python3.10.3/usr/local/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/loader.py", line 434, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/loader.py", line 357, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
AttributeError: 'map' object has no attribute 'extend'

```

If just for fun I then execute `nosetests positions --verbose --nocapture --verbosity=2` without using `manage.py` that comes with django, I get the result in the original description above. Using 1.4.0 without django leads to some other errors that seem to be django related:

|  | 1.4.0 | 1.4.3|
| --------------- | --------------- | --------------- |
|django | OK | error1 above |
|nosetest only | error2 | error1 above |

The error1 prototype seems to be the following:
```
$ python
Python 3.10.3 (main, Mar 22 2022, 13:00:21) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> a = map(lambda x: x + 1, [2,3])
>>> a.extend
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'map' object has no attribute 'extend'
```
Which presumably could arise from line 335 in loader.py, where it says
```
tests = map(lambda t: self.makeTest(t, parent=module),
         test_classes + test_funcs)
```
followed by
`tests.extend(self.loadTestsFromDir(module_path))`
at line 357, which maybe expects `tests` to be a `list` rather than a `map`

Replacing line 335 with
```
            tests = list(map(lambda t: self.makeTest(t, parent=module),
                        test_classes + test_funcs))
```
seems to remove this exception, but then I get another one:
```
======================================================================
ERROR: Failure: AttributeError ('function' object has no attribute 'im_class')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dauser/projects/daproject/venv/daproject/lib/python3.10/site-packages/nose/failure.py", line 40, in runTest
    raise self.exc_val(None).with_traceback(self.tb)
TypeError: --------------------- >> end captured logging << ---------------------
```
I'll stay with 1.4.0 for the time being ;-)

**Comment by FriedrichFroebel** [comment]
I just stumbled upon the same *AttributeError* with the latest 1.4.3 release. Pinning the version to 1.4.0 seems to work fine. As I only need this package to migrate some old legacy Python 2 code written with *nose* tests to Python 3 which will not use *nose* any more, this is no big deal here and therefore I did no further research on this topic.

**Comment by atsb** [comment]
I've looked into this quite a bit but have not found the reason.  It works fine for my projects on three separate installations, however this could be because I wipe the previous version and install fresh. There were quite a few changes from 1.4.0 to 1.4.3 and upgrading from that could indeed cause issues.

**Comment by FriedrichFroebel** [comment]
In my case, I explicitly installed the *nose-py3* package in a clean CI environment here on GitHub Actions, so in theory there should not be such a conflict. Adding on the comment from @odmi-frijt, the offending *map* call is limited to `not discovered or self.selector.wantModule(module)`, so you might run into a different path inside your projects and never call *map* there.

If you want to further debug this: My test repository is a fork of https://github.com/jwilk-archive/ocrodjvu, which I tested with exactly the code of the base repository. This code is still Python2-only, but this should not be the problem, as I got the aforementioned error when simply doing `python -m pip install nose-py3 && make test` while on Python 3.

**Comment by atsb** [comment]
Thanks!  I'll get on that

**Comment by obriencj** [comment]
I managed to fix this but went down a bit of a rabbit hole trying to get selftest to work as well.

There were piles of bare prints left over in the unit testing, so I suspect they were never ported over and not running at all.

If you're interested, I'll submit a PR of the WIP that contains a fix for both trying to extend a map, and the followup of the leftover im_class python2 bound method checking. I've verified at least that this allows my own tests to be run, but since I cannot get self testing to even remotely pass yet, it's hard to tell what else might be broken for now.

https://github.com/obriencj/nose-py3/tree/map_extend

[FriedrichFroebel](https://github.com/FriedrichFroebel) if you'd be interested in trying to see if my fixes also work in your environment, you can set the dependency entry in tox to be eg. `git+https://github.com/obriencj/nose-py3.git@map_extend#egg=nose-py3`

**Comment by FriedrichFroebel** [comment]
I just did a quick test with the aforementioned legacy codebase and the `map_extend` branch on Python 3.10 and can confirm that the (recent?) NumPy and collection error did not occur.

**Comment by atsb** [comment]
> I managed to fix this but went down a bit of a rabbit hole trying to get selftest to work as well.
> 
> There were piles of bare prints left over in the unit testing, so I suspect they were never ported over and not running at all.
> 
> If you're interested, I'll submit a PR of the WIP that contains a fix for both trying to extend a map, and the followup of the leftover im_class python2 bound method checking. I've verified at least that this allows my own tests to be run, but since I cannot get self testing to even remotely pass yet, it's hard to tell what else might be broken for now.
> 
> https://github.com/obriencj/nose-py3/tree/map_extend
> 
> [FriedrichFroebel](https://github.com/FriedrichFroebel) if you'd be interested in trying to see if my fixes also work in your environment, you can set the dependency entry in tox to be eg. `git+https://github.com/obriencj/nose-py3.git@map_extend#egg=nose-py3`

A PR would be appreciated.  I haven't had a chance to look into it yet.  The tests themselves are still broken due to many Python 2'isms.  I'm going to convert these next year so the entire codebase can be properly tested within python 3.10 as a minimum.
