### ISSUE TITLE
TypeError: 'AttributeError' object is not iterable

### ISSUE THREAD

**Issue by jschueller** [atsb/nose-py3#21]
I have a new error in nose with 1.6.8 when an error occurs:
```
 tests.test_fmi.Test_FMUModelBase2.test_simulation_with_syncronization_CS ... Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/unittest/case.py", line 651, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/unittest/case.py", line 600, in run
    self._feedErrorsToResult(result, outcome.errors)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/unittest/case.py", line 519, in _feedErrorsToResult
    result.addError(test, exc_info)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nose/proxy.py", line 134, in addError
    formatted = plugins.formatError(self.test, err)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nose/plugins/manager.py", line 90, in __call__
    return self.call(*arg, **kw)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nose/plugins/manager.py", line 132, in chain
    result = meth(*arg, **kw)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nose/plugins/logcapture.py", line 253, in formatError
    return (ec, self.addCaptureToErr(ev, records), tb)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nose/plugins/logcapture.py", line 260, in addCaptureToErr
    [safe_str(ev), ln('>> begin captured logging <<')],
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nose/util.py", line 657, in safe_str
    return ' '.join([safe_str(arg, encoding)
TypeError: 'AttributeError' object is not iterable
```
any idea ?

**Comment by obriencj** [comment]
@jschueller  would you please attempt this again using this as the nose-py3 dep
`git+https://github.com/obriencj/nose-py3@safer_str` -- you may need to clean your tox env (if using tox)

**Comment by jschueller** [comment]
yes, that seems to fix it

**Comment by obriencj** [comment]
Great! In addition, could you confirm that the test output (which I guess is a failure) is as you'd expect it to be?

**Comment by jschueller** [comment]
yes I can see the correct error

**Comment by obriencj** [comment]
Wonderful. I apologize, as I'm the one that introduced this bug when I was trying to fight with the numpy 2.0.0 update removing the unicode helper. Thank you very much for validating the fix has reasonable output.

**Comment by atsb** [comment]
1.6.9 is on pypi now with the fix

**Comment by jschueller** [comment]
see #22
