### ISSUE TITLE
xunit plugin fails with TypeError: expected string or bytes-like object, got 'TestResult'

### ISSUE THREAD

**Issue by amfleurke** [atsb/nose-py3#9]
I upgraded from Python 3.6.8 to python 3.11.2 and to nose-py3 1.6.1. 
If I run nosetests, my tests succeed, but when adding --with-xunit argument to the nose command, the tests fail

I get 
```
starting nosetests:
test__init__ (common.test_connectionpool.TestConnectionPool.test__init__) ... Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nose/case.py", line 134, in run
    self.runTest(result)
  File "/usr/local/lib/python3.11/site-packages/nose/case.py", line 152, in runTest
    test(result)
  File "/usr/local/lib/python3.11/unittest/case.py", line 678, in __call__
    return self.run(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/unittest/case.py", line 636, in run
    result.addSuccess(self)
  File "/usr/local/lib/python3.11/site-packages/nose/proxy.py", line 168, in addSuccess
    self.plugins.addSuccess(self.test)
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/manager.py", line 93, in __call__
    return self.call(*arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/manager.py", line 161, in simple
    result = meth(*arg, **kw)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/xunit.py", line 356, in addSuccess
    {'cls': self._getCls(id),
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/xunit.py", line 188, in _getCls
    return self._quoteattr(id_split(id)[0])
                           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/xunit.py", line 80, in id_split
    m = TEST_ID.match(idval)
        ^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'TestResult'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/core.py", line 117, in __init__
    unittest.TestProgram.__init__(
  File "/usr/local/lib/python3.11/unittest/main.py", line 102, in __init__
    self.runTests()
  File "/usr/local/lib/python3.11/site-packages/nose/core.py", line 206, in runTests
    result = self.testRunner.run(self.test)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/core.py", line 61, in run
    test(result)
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 176, in __call__
    return self.run(*arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 221, in run
    test(orig)
  File "/usr/local/lib/python3.11/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 73, in run
    test(result)
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 176, in __call__
    return self.run(*arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 221, in run
    test(orig)
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 176, in __call__
    return self.run(*arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 221, in run
    test(orig)
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 176, in __call__
    return self.run(*arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 221, in run
    test(orig)
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 176, in __call__
    return self.run(*arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/suite.py", line 221, in run
    test(orig)
  File "/usr/local/lib/python3.11/site-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/case.py", line 139, in run
    result.addError(self, err)
  File "/usr/local/lib/python3.11/site-packages/nose/proxy.py", line 137, in addError
    plugins.addError(self.test, err)
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/manager.py", line 93, in __call__
    return self.call(*arg, **kw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/manager.py", line 161, in simple
    result = meth(*arg, **kw)
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/xunit.py", line 314, in addError
    {'cls': self._getCls(id),
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/xunit.py", line 188, in _getCls
    return self._quoteattr(id_split(id)[0])
                           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nose/plugins/xunit.py", line 80, in id_split
    m = TEST_ID.match(idval)
        ^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'TestResult'
```

**Comment by atsb** [comment]
Thanks for this!  Plugins are still a work in progress.  I'll get this fixed

**Comment by atsb** [comment]
I've pushed a fix to this and tagged the issue in the commit.  If this still happens for you, let me know and re-open this.  If it is all good for you, then I will release a 1.6.2 version to pypi.

**Comment by amfleurke** [comment]
Looking good! Thanks for the patch!
